# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11b8c765d7a5e940ecc7a3c765fc5312d52b15c8075b78fa1a82e69815dcf3e21e7d39e21f117196faeb1068d9158535409829a4902faae3b3b0023dee30955f

test:
  secret_key_base: e448eeb54914356b9b338f997f2cef7400839c6529267377d57aed9488bccaca98ca5d200933a652ba8b6f1dc8fc67bc484e3b26fcf624e14f4c1db08a596994

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
